### ISSUE TITLE
Look at installed software automation.

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/mkdocs-rc-docs#10]
- [x] - generating a list of available packages (from modules repo?)
- [x] - generating a list of R packages
- [x] - generating a list of Python packages

**Comment by ikirker** [comment]
Current thinking:

- we can clone the modulefiles repository on the Travis build server. I'm not really sure what format is best for this, or whether it should be one or a few pages, but we can pull out names, versions, variants, and whatever passes for a description someone has set. (i.e. `module-whatis`) It'll be pretty rough.

- I *really*, ***really*** don't want to get into the business of pushing files between the clusters and the webserver. It sounds like an operational and security nightmare.

- I don't really want to get into the business of relying on Aristotle to generate files into some `~ccspapp/html.pub` directory either, that sounds flaky as hell.

- For Python, we can take the list of packages and grab a description from PyPi for each of them. This won't get installed dependencies, though, just the things we meant to install -- not *necessarily* a problem if you take the view that we only guarantee to have installed the things we meant to install? And it won't aggregate installed version information.

- There's a similar problem in R, made worse by the fact that we grab R packages from a shedload of increasingly questionable sources. I *suspect* a running copy of R has version and description information about all installed packages, but see the above comments about pushing files around.

- It would, in theory, be possible to load up a copy of Python and R in Travis and run through our package install lists. Pretty wasteful, though, and with a high likelihood of timing out.

**Comment by ikirker** [comment]
There. It's awful. I hate it. It's an unusable, inaccessible mess, but it's

![Done.](https://user-images.githubusercontent.com/479061/67708674-6f679680-f9b4-11e9-9678-cfc3abd4a7b5.png)
