### ISSUE TITLE
Qsub emailing option error

### ISSUE THREAD

**Issue by andyembleton** [UCL-RITS/mkdocs-rc-docs#13]
I do not think the 'comma between options' for the mailing line is correct. This did not work for me until I removed the comma and simply put _-m be_ for example.
https://github.com/UCL-RITS/mkdocs-rc-docs/blob/master/mkdocs-project-dir/docs/Job_Results.md#qsub-emailing

**Comment by ikirker** [comment]
Hm, yeah, I think you're right, even if the manpage says otherwise:
```
-m b|e|a|s|n,...
```

I'll try to check this against the implementation.

Thanks for making an issue for this, sorry it took a while for someone to reply.

**Comment by ikirker** [comment]
(I'd check it against the version on the clusters, but... they're all down.)

**Comment by ikirker** [comment]
Confirmed and fixed. Thanks!
