### ISSUE TITLE
Remove references from docs that suggest that Grace is active

### ISSUE THREAD

**Issue by krishnakumarg1984** [UCL-RITS/mkdocs-rc-docs#50]
The following sentence in the [page on Kathleen](https://www.rc.ucl.ac.uk/docs/Clusters/Kathleen/) seems to suggest that Grace is indeed active

>You can connect directly in both directions between Grace and Kathleen.

This sentence should perhaps be deleted?

**Comment by DanielChau128** [comment]
Mention of Grace has been removed.
