### ISSUE TITLE
Typo in FQDN for ssh-gateway in aristotle connection docs

### ISSUE THREAD

**Issue by krishnakumarg1984** [UCL-RITS/mkdocs-rc-docs#52]
In the [Remote Access](https://www.rc.ucl.ac.uk/docs/Remote_Access/) & [HowTo](https://www.rc.ucl.ac.uk/docs/howto/) pages, the connection information for `aristotle` has a typo in the FQDN for the gateway jump host.

```
Host aristotle
   User ccxxxxx
   HostName aristotle.rc.ucl.ac.uk
   proxyCommand ssh -W aristotle.rc.ucl.ac.uk:22 ccxxxxx@ssh-gateway.rc.ucl.ac.uk
```

The gateway does not have `rc`, and should simply be `ssh-gateway.ucl.ac.uk`.

**Comment by heatherkellyucl** [comment]
Oh, that's because the ssh-gateway *used* to have `rc` when it was first set up.

**Comment by heatherkellyucl** [comment]
I'm not seeing that in the HowTo page, but RemoteAccess is updated now.
