### ISSUE TITLE
Invalid/404 links in docs

### ISSUE THREAD

**Issue by krishnakumarg1984** [UCL-RITS/mkdocs-rc-docs#53]
The documentation points to:
- https://www.rc.ucl.ac.uk/docs/Example_Jobscripts/Glossary#Core 
- https://www.rc.ucl.ac.uk/docs/Reporting_problems

both of which are non-existent (404) links.

**Comment by DanielChau128** [comment]
I was only able to find two places which had those broken links:

- https://www.rc.ucl.ac.uk/docs/Example_Jobscripts/#multi-threaded-job-example
- https://www.rc.ucl.ac.uk/docs/#how-to

I have removed them.
